//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleEntityF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYE
    {
        public EMPLOYE()
        {
            this.EMPLOYE1 = new HashSet<EMPLOYE>();
            this.INSCRITs = new HashSet<INSCRIT>();
        }
    
        public decimal NUMEMP { get; set; }
        public string NOMEMP { get; set; }
        public string PRENOMEMP { get; set; }
        public string POSTE { get; set; }
        public decimal SALAIRE { get; set; }
        public Nullable<decimal> PRIME { get; set; }
        public string CODEPROJET { get; set; }
        public Nullable<decimal> SUPERIEUR { get; set; }
    
        public virtual ICollection<EMPLOYE> EMPLOYE1 { get; set; }
        public virtual EMPLOYE EMPLOYE2 { get; set; }
        public virtual PROJET PROJET { get; set; }
        public virtual ICollection<INSCRIT> INSCRITs { get; set; }

        public override string ToString()
        {
            return NUMEMP + " - " + NOMEMP + " - " + POSTE + " - " + SALAIRE + " - " + ((PRIME == null) ? 0 : PRIME) + " + " + ((CODEPROJET == null) ? "NULL" : CODEPROJET) + " - " + SUPERIEUR==null ?  "NULL";
                
        }
    }
}
