//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleEntityF
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSCRIT
    {
        public INSCRIT()
        {
            this.PARTICIPERs = new HashSet<PARTICIPER>();
        }
    
        public decimal NUMEMP { get; set; }
        public string CODESEMI { get; set; }
        public System.DateTime DATEINSCRIT { get; set; }
    
        public virtual EMPLOYE EMPLOYE { get; set; }
        public virtual SEMINAIRE SEMINAIRE { get; set; }
        public virtual ICollection<PARTICIPER> PARTICIPERs { get; set; }
    }
}
